/*     */ package shame.astra.api.storages.implement.helpertstorages.enumvar;
/*     */ import shame.astra.client.modules.impl.combat.ElytraResolver;
/*     */ import shame.astra.client.modules.impl.combat.TriggerBot;
/*     */ import shame.astra.client.modules.impl.misc.LeaveTracker;
/*     */ import shame.astra.client.modules.impl.player.AutoForest;
/*     */ import shame.astra.client.modules.impl.player.ChestStealer;
/*     */ import shame.astra.client.modules.impl.render.LineGlyphes;
/*     */ import shame.astra.client.modules.impl.render.Particle;
/*     */ import shame.astra.client.modules.impl.render.ShulkerPreview;
/*     */ 
/*     */ public interface ModuleRewords {
/*  12 */   public static final AirStuck airStuck = AirStuck.INSTANCE;
/*  13 */   public static final Arrows arrows = Arrows.INSTANCE;
/*  14 */   public static final Aura aura = Aura.INSTANCE;
/*  15 */   public static final AntiBot antibot = AntiBot.INSTANCE;
/*  16 */   public static final AutoAccept autoAccept = AutoAccept.INSTANCE;
/*  17 */   public static final AutoArmor autoArmor = AutoArmor.INSTANCE;
/*  18 */   public static final AutoFish autoFish = AutoFish.INSTANCE;
/*  19 */   public static final AutoForest autoForest = AutoForest.INSTANCE;
/*  20 */   public static final DeathCoord deathCoord = DeathCoord.INSTANCE;
/*  21 */   public static final LeaveTracker leavetracker = LeaveTracker.INSTANCE;
/*  22 */   public static final EcOpen ecopen = EcOpen.INSTANCE;
/*  23 */   public static final AutoBuy autoBuy = AutoBuy.INSTANCE;
/*  24 */   public static final AutoDuel autoDuel = AutoDuel.INSTANCE;
/*  25 */   public static final AutoEat autoEat = AutoEat.INSTANCE;
/*  26 */   public static final AutoLeave autoLeave = AutoLeave.INSTANCE;
/*  27 */   public static final AutoExplosion autoExplosion = AutoExplosion.INSTANCE;
/*  28 */   public static final AutoJoin autoJoin = AutoJoin.INSTANCE;
/*  29 */   public static final AutoPvp autoPvp = AutoPvp.INSTANCE;
/*  30 */   public static final NameProtect nameProtect = NameProtect.INSTANCE;
/*  31 */   public static final AutoJump autoJump = AutoJump.INSTANCE;
/*  32 */   public static final ChestStealer chestStealer = ChestStealer.INSTANCE;
/*  33 */   public static final ClientSounds clientSounds = ClientSounds.INSTANCE;
/*  34 */   public static final AutoTool autoTool = AutoTool.INSTANCE;
/*  35 */   public static final AutoTotem autoTotem = AutoTotem.INSTANCE;
/*  36 */   public static final AutoTrap autoTrap = AutoTrap.INSTANCE;
/*  37 */   public static final BlockOverlay blockOverlay = BlockOverlay.INSTANCE;
/*  38 */   public static final ClickPearl clickPearl = ClickPearl.INSTANCE;
/*  39 */   public static final Cosmetics cosmetics = Cosmetics.INSTANCE;
/*  40 */   public static final Cubes cubes = Cubes.INSTANCE;
/*  41 */   public static final KillEffect killEffect = KillEffect.INSTANCE;
/*  42 */   public static final BlockESP blockesp = BlockESP.INSTANCE;
/*  43 */   public static final ElytraBoost elytraBoost = ElytraBoost.INSTANCE;
/*  44 */   public static final ElytraMotion elytraMotion = ElytraMotion.INSTANCE;
/*  45 */   public static final ElytraSwap elytraSwap = ElytraSwap.INSTANCE;
/*  46 */   public static final ElytraTarget elytraTarget = ElytraTarget.INSTANCE;
/*  47 */   public static final ElytraResolver elytraresolver = ElytraResolver.INSTANCE;
/*  48 */   public static final EntityESP entityESP = EntityESP.INSTANCE;
/*  49 */   public static final Flight flight = Flight.INSTANCE;
/*  50 */   public static final FreeCam freeCam = FreeCam.INSTANCE;
/*  51 */   public static final FullBright fullBright = FullBright.INSTANCE;
/*  52 */   public static final GrimNoFall grimNoFall = GrimNoFall.INSTANCE;
/*  53 */   public static final GrimGlide grimGlide = GrimGlide.INSTANCE;
/*  54 */   public static final HighJump highJump = HighJump.INSTANCE;
/*  55 */   public static final HelpMessage helpMessage = HelpMessage.INSTANCE;
/*  56 */   public static final HitBubbles hitBubbles = HitBubbles.INSTANCE;
/*  57 */   public static final Interface interfaceModule = Interface.INSTANCE;
/*  58 */   public static final InterpolateF5 interpolateF5 = InterpolateF5.INSTANCE;
/*  59 */   public static final InventoryWalk inventoryWalk = InventoryWalk.INSTANCE;
/*  60 */   public static final ItemAim itemAim = ItemAim.INSTANCE;
/*  61 */   public static final ItemScroller itemScroller = ItemScroller.INSTANCE;
/*  62 */   public static final ItemRelease itemRelease = ItemRelease.INSTANCE;
/*  63 */   public static final JumpCircle jumpCircle = JumpCircle.INSTANCE;
/*  64 */   public static final KTLeave kTLeave = KTLeave.INSTANCE;
/*  65 */   public static final LineGlyphes lineGlyphes = LineGlyphes.INSTANCE;
/*  66 */   public static final LockSlot lockSlot = LockSlot.INSTANCE;
/*  67 */   public static final NoClip noClip = NoClip.INSTANCE;
/*  68 */   public static final NoJumpDelay noJumpDelay = NoJumpDelay.INSTANCE;
/*  69 */   public static final Nuker nuker = Nuker.INSTANCE;
/*  70 */   public static final NoPush noPush = NoPush.INSTANCE;
/*  71 */   public static final NoVelocity noVelocity = NoVelocity.INSTANCE;
/*  72 */   public static final NoVignette noVignette = NoVignette.INSTANCE;
/*  73 */   public static final NoControllerWeb noControllerWeb = NoControllerWeb.INSTANCE;
/*  74 */   public static final NoWeb noWeb = NoWeb.INSTANCE;
/*  75 */   public static final PacketCriticals packetCriticals = PacketCriticals.INSTANCE;
/*  76 */   public static final Particle particle = Particle.INSTANCE;
/*  77 */   public static final PlayerFakeLags playerFakeLags = PlayerFakeLags.INSTANCE;
/*  78 */   public static final Projectile projectile = Projectile.INSTANCE;
/*  79 */   public static final FireworkESP fireworkESP = FireworkESP.INSTANCE;
/*  80 */   public static final FastBreak fastBreak = FastBreak.INSTANCE;
/*  81 */   public static final FastExp fastExp = FastExp.INSTANCE;
/*  82 */   public static final Removals removals = Removals.INSTANCE;
/*  83 */   public static final RPSpoofer rPSpoofer = RPSpoofer.INSTANCE;
/*  84 */   public static final SeeInvisibles seeInvisibles = SeeInvisibles.INSTANCE;
/*  85 */   public static final ShaderEsp shaderEsp = ShaderEsp.INSTANCE;
/*  86 */   public static final ShaderHands shaderHands = ShaderHands.INSTANCE;
/*  87 */   public static final Satellite sattelite = Satellite.INSTANCE;
/*  88 */   public static final ShulkerPreview shulkerPreview = ShulkerPreview.INSTANCE;
/*  89 */   public static final Sonar sonar = Sonar.INSTANCE;
/*  90 */   public static final Speed speed = Speed.INSTANCE;
/*  91 */   public static final Sprint sprint = Sprint.INSTANCE;
/*  92 */   public static final SwingAnimations swingAnimations = SwingAnimations.INSTANCE;
/*  93 */   public static final TargetESP targetESP = TargetESP.INSTANCE;
/*  94 */   public static final TargetPearl targetPearl = TargetPearl.INSTANCE;
/*  95 */   public static final Timer timer = Timer.INSTANCE;
/*  96 */   public static final TotemAngel totemAngel = TotemAngel.INSTANCE;
/*  97 */   public static final TpBack tpBack = TpBack.INSTANCE;
/*  98 */   public static final TpsSync tpsSync = TpsSync.INSTANCE;
/*  99 */   public static final TpLoot tpLoot = TpLoot.INSTANCE;
/* 100 */   public static final ViewModel viewModel = ViewModel.INSTANCE;
/* 101 */   public static final WorldTweaks worldTweaks = WorldTweaks.INSTANCE;
/* 102 */   public static final XCarry xCarry = XCarry.INSTANCE;
/* 103 */   public static final AutoSwap autoSwap = AutoSwap.INSTANCE;
/* 104 */   public static final AimBot aimBot = AimBot.INSTANCE;
/* 105 */   public static final TriggerBot triggerBot = TriggerBot.INSTANCE;
/* 106 */   public static final NoSlow noSlow = NoSlow.INSTANCE;
/* 107 */   public static final ScoreboardHP scoreboardHP = ScoreboardHP.INSTANCE;
/* 108 */   public static final Step step = Step.INSTANCE;
/* 109 */   public static final ServerHelper serverHelper = ServerHelper.INSTANCE;
/* 110 */   public static final Spider spider = Spider.INSTANCE;
/* 111 */   public static final LootTracker lootTracker = LootTracker.INSTANCE;
/* 112 */   public static final HitMarker hitMarker = HitMarker.INSTANCE;
/* 113 */   public static final Trails trails = Trails.INSTANCE;
/* 114 */   public static final Trajectories trajectories = Trajectories.INSTANCE;
/*     */ }


/* Location:              C:\User\\user\Downloads\astra-1.0.0.jar!\shame\astra\api\storages\implement\helpertstorages\enumvar\ModuleRewords.class
 * Java compiler version: 21 (65.0)
 * JD-Core Version:       1.1.3
 */